# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "Windows" ]
  pull_request:
    branches: [ "Windows" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 3.12로 파이썬 테스트
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: 필요항목 다운로드
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 파이썬 테스트
    - timeout-minutes: 1
      run: |
        py isddcmd.py
