name: 파이썬 테스트

on:
  push:
    paths-ignore: ".github/workflows/main.yml"
    branches: [ "Windows" ]
  pull_request:
    branches: [ "Windows" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 3.12로 파이썬 테스트
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: 필요항목 다운로드
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 파이썬 테스트
      run: |
        python isddcmd.py automated
      timeout-minutes: 1
